export const featureConfig = [
  {
    key: 'brand-profiles',
    title: 'Brand Profiles',
    description: 'Define and manage brand voice characteristics, tone attributes, and personality traits',
    icon: 'Fingerprint',
    color: '#6366f1',
    gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    apiPath: '/api/brand-profiles',
    fields: [
      { name: 'name', label: 'Brand Name', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'industry', label: 'Industry', type: 'text' },
      { name: 'tone_attributes', label: 'Tone Attributes', type: 'tags', placeholder: 'e.g. professional, warm, bold' },
      { name: 'personality_traits', label: 'Personality Traits', type: 'tags', placeholder: 'e.g. trustworthy, innovative' },
      { name: 'target_audience', label: 'Target Audience', type: 'text' },
      { name: 'brand_values', label: 'Brand Values', type: 'tags', placeholder: 'e.g. quality, integrity' },
    ],
    columns: ['name', 'industry', 'target_audience'],
    hasAI: false,
  },
  {
    key: 'content-analysis',
    title: 'Content Analysis',
    description: 'AI-powered analysis of content for brand voice consistency across channels',
    icon: 'FileSearch',
    color: '#ec4899',
    gradient: 'linear-gradient(135deg, #ec4899, #f43f5e)',
    apiPath: '/api/content-analysis',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'content', label: 'Content to Analyze', type: 'textarea', required: true },
      { name: 'brand_profile_id', label: 'Brand Profile', type: 'select', optionsFrom: 'brand-profiles' },
      { name: 'channel', label: 'Channel', type: 'select', options: ['website', 'social_media', 'email', 'blog', 'press', 'print', 'app_store'] },
    ],
    columns: ['title', 'channel', 'consistency_score', 'status'],
    hasAI: true,
    aiField: 'ai_analysis',
    scoreField: 'consistency_score',
  },
  {
    key: 'tone-detection',
    title: 'Tone Detection',
    description: 'Detect and analyze the tone of your content using AI-powered analysis',
    icon: 'AudioWaveform',
    color: '#f59e0b',
    gradient: 'linear-gradient(135deg, #f59e0b, #f97316)',
    apiPath: '/api/tone-detection',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'content', label: 'Content', type: 'textarea', required: true },
      { name: 'expected_tone', label: 'Expected Tone', type: 'select', options: ['professional', 'casual', 'warm', 'urgent', 'inspirational', 'informative', 'playful', 'authoritative', 'empathetic', 'motivational'] },
    ],
    columns: ['title', 'expected_tone', 'detected_tone', 'confidence', 'status'],
    hasAI: true,
    aiField: 'ai_analysis',
    scoreField: 'confidence',
  },
  {
    key: 'style-guide',
    title: 'Style Guide Rules',
    description: 'Manage brand-specific writing rules, formatting guidelines, and standards',
    icon: 'BookOpen',
    color: '#10b981',
    gradient: 'linear-gradient(135deg, #10b981, #14b8a6)',
    apiPath: '/api/style-guide',
    fields: [
      { name: 'rule_name', label: 'Rule Name', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'select', options: ['Grammar', 'Punctuation', 'Vocabulary', 'Readability', 'Formatting', 'Tone', 'Structure', 'Accessibility'] },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'examples', label: 'Examples', type: 'tags', placeholder: 'Add examples' },
      { name: 'severity', label: 'Severity', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { name: 'brand_profile_id', label: 'Brand Profile', type: 'select', optionsFrom: 'brand-profiles' },
    ],
    columns: ['rule_name', 'category', 'severity'],
    hasAI: false,
  },
  {
    key: 'channels',
    title: 'Channel Management',
    description: 'Configure and manage brand voice guidelines for each communication channel',
    icon: 'Radio',
    color: '#3b82f6',
    gradient: 'linear-gradient(135deg, #3b82f6, #6366f1)',
    apiPath: '/api/channels',
    fields: [
      { name: 'name', label: 'Channel Name', type: 'text', required: true },
      { name: 'type', label: 'Type', type: 'select', options: ['website', 'social_media', 'email', 'content', 'video', 'press', 'support', 'app', 'print', 'event', 'messaging', 'audio'] },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'guidelines', label: 'Voice Guidelines', type: 'textarea' },
      { name: 'brand_profile_id', label: 'Brand Profile', type: 'select', optionsFrom: 'brand-profiles' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'archived'] },
    ],
    columns: ['name', 'type', 'status'],
    hasAI: false,
  },
  {
    key: 'content-scoring',
    title: 'Content Scoring',
    description: 'AI-powered scoring of content against brand voice criteria and benchmarks',
    icon: 'BarChart3',
    color: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #8b5cf6, #a855f7)',
    apiPath: '/api/content-scoring',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'content', label: 'Content to Score', type: 'textarea', required: true },
      { name: 'brand_profile_id', label: 'Brand Profile', type: 'select', optionsFrom: 'brand-profiles' },
      { name: 'scoring_criteria', label: 'Scoring Criteria', type: 'select', options: ['brand_voice_alignment', 'tone_consistency', 'engagement_potential', 'professionalism', 'age_appropriateness', 'technical_accuracy', 'clarity', 'luxury_positioning', 'motivational_impact', 'trust_building'] },
    ],
    columns: ['title', 'scoring_criteria', 'overall_score', 'status'],
    hasAI: true,
    aiField: 'ai_analysis',
    scoreField: 'overall_score',
  },
  {
    key: 'vocabulary',
    title: 'Vocabulary Management',
    description: 'Manage approved, banned, and restricted brand vocabulary terms',
    icon: 'Library',
    color: '#14b8a6',
    gradient: 'linear-gradient(135deg, #14b8a6, #06b6d4)',
    apiPath: '/api/vocabulary',
    fields: [
      { name: 'term', label: 'Term', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'select', options: ['action_words', 'business', 'descriptors', 'technical', 'luxury', 'motivational', 'pet', 'quality', 'travel'] },
      { name: 'status', label: 'Status', type: 'select', options: ['approved', 'banned', 'restricted'] },
      { name: 'definition', label: 'Definition', type: 'textarea' },
      { name: 'usage_example', label: 'Usage Example', type: 'textarea' },
      { name: 'brand_profile_id', label: 'Brand Profile', type: 'select', optionsFrom: 'brand-profiles' },
    ],
    columns: ['term', 'category', 'status'],
    hasAI: false,
  },
  {
    key: 'competitor-analysis',
    title: 'Competitor Analysis',
    description: 'AI-driven analysis of competitor brand voices and differentiation opportunities',
    icon: 'Swords',
    color: '#ef4444',
    gradient: 'linear-gradient(135deg, #ef4444, #f97316)',
    apiPath: '/api/competitor-analysis',
    fields: [
      { name: 'competitor_name', label: 'Competitor Name', type: 'text', required: true },
      { name: 'industry', label: 'Industry', type: 'text' },
      { name: 'sample_content', label: 'Sample Content', type: 'textarea', required: true },
      { name: 'brand_profile_id', label: 'Brand Profile', type: 'select', optionsFrom: 'brand-profiles' },
    ],
    columns: ['competitor_name', 'industry', 'status'],
    hasAI: true,
    aiField: 'ai_analysis',
  },
  {
    key: 'content-templates',
    title: 'Content Templates',
    description: 'Pre-built templates aligned with brand voice for consistent content creation',
    icon: 'LayoutTemplate',
    color: '#06b6d4',
    gradient: 'linear-gradient(135deg, #06b6d4, #0ea5e9)',
    apiPath: '/api/content-templates',
    fields: [
      { name: 'name', label: 'Template Name', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'select', options: ['marketing', 'content', 'pr', 'social_proof', 'support', 'ecommerce', 'hr', 'customer_success', 'feedback'] },
      { name: 'channel', label: 'Channel', type: 'select', options: ['email', 'social_media', 'blog', 'website', 'press', 'video', 'print'] },
      { name: 'template_content', label: 'Template Content', type: 'textarea', required: true },
      { name: 'variables', label: 'Variables', type: 'tags', placeholder: 'e.g. customer_name, product' },
      { name: 'brand_profile_id', label: 'Brand Profile', type: 'select', optionsFrom: 'brand-profiles' },
    ],
    columns: ['name', 'category', 'channel'],
    hasAI: false,
  },
  {
    key: 'audit-reports',
    title: 'Voice Audit Reports',
    description: 'AI-generated comprehensive audit reports on brand voice consistency',
    icon: 'ClipboardCheck',
    color: '#f43f5e',
    gradient: 'linear-gradient(135deg, #f43f5e, #e11d48)',
    apiPath: '/api/audit-reports',
    fields: [
      { name: 'title', label: 'Report Title', type: 'text', required: true },
      { name: 'brand_profile_id', label: 'Brand Profile', type: 'select', optionsFrom: 'brand-profiles' },
      { name: 'audit_scope', label: 'Audit Scope', type: 'select', options: ['All channels', 'Social media channels', 'Email marketing', 'Website content', 'Print materials', 'Customer support', 'Full brand audit'] },
    ],
    columns: ['title', 'audit_scope', 'overall_score', 'status'],
    hasAI: true,
    aiField: 'ai_analysis',
    scoreField: 'overall_score',
  },
  {
    key: 'team-members',
    title: 'Team Members',
    description: 'Manage team access, roles, and brand assignment for content creators',
    icon: 'Users',
    color: '#a855f7',
    gradient: 'linear-gradient(135deg, #a855f7, #c084fc)',
    apiPath: '/api/team-members',
    fields: [
      { name: 'name', label: 'Full Name', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'text', required: true },
      { name: 'role', label: 'Role', type: 'text' },
      { name: 'department', label: 'Department', type: 'select', options: ['Marketing', 'Content', 'Design', 'Digital', 'Communications', 'Product', 'Analytics', 'Media', 'Legal', 'International'] },
      { name: 'brand_profile_id', label: 'Brand Profile', type: 'select', optionsFrom: 'brand-profiles' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
    ],
    columns: ['name', 'role', 'department', 'status'],
    hasAI: false,
  },
  {
    key: 'content-history',
    title: 'Content History',
    description: 'Track content versions, changes, and evolution over time',
    icon: 'History',
    color: '#64748b',
    gradient: 'linear-gradient(135deg, #64748b, #475569)',
    apiPath: '/api/content-history',
    fields: [
      { name: 'title', label: 'Content Title', type: 'text', required: true },
      { name: 'content', label: 'Content', type: 'textarea' },
      { name: 'channel', label: 'Channel', type: 'text' },
      { name: 'author', label: 'Author', type: 'text' },
      { name: 'version', label: 'Version', type: 'text' },
      { name: 'brand_profile_id', label: 'Brand Profile', type: 'select', optionsFrom: 'brand-profiles' },
      { name: 'change_type', label: 'Change Type', type: 'select', options: ['created', 'updated', 'reviewed', 'approved', 'archived'] },
    ],
    columns: ['title', 'channel', 'author', 'version', 'change_type'],
    hasAI: false,
  },
  {
    key: 'ai-suggestions',
    title: 'AI Suggestions',
    description: 'Get AI-powered suggestions to improve content for brand voice consistency',
    icon: 'Sparkles',
    color: '#f59e0b',
    gradient: 'linear-gradient(135deg, #f59e0b, #eab308)',
    apiPath: '/api/ai-suggestions',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'original_content', label: 'Original Content', type: 'textarea', required: true },
      { name: 'suggestion_type', label: 'Suggestion Type', type: 'select', options: ['tone_enhancement', 'brand_alignment', 'style_upgrade', 'formality_adjustment', 'simplification', 'premium_positioning', 'clarity_improvement', 'luxury_enhancement', 'energy_boost', 'emotional_connection', 'storytelling', 'empathy_addition', 'sustainability_focus', 'conciseness', 'sophistication'] },
      { name: 'brand_profile_id', label: 'Brand Profile', type: 'select', optionsFrom: 'brand-profiles' },
    ],
    columns: ['title', 'suggestion_type', 'status'],
    hasAI: true,
    aiField: 'ai_suggestion',
  },
  {
    key: 'sentiment-analysis',
    title: 'Sentiment Analysis',
    description: 'AI-powered sentiment analysis for brand content emotional impact assessment',
    icon: 'Heart',
    color: '#ec4899',
    gradient: 'linear-gradient(135deg, #ec4899, #f472b6)',
    apiPath: '/api/sentiment-analysis',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'content', label: 'Content to Analyze', type: 'textarea', required: true },
      { name: 'brand_profile_id', label: 'Brand Profile', type: 'select', optionsFrom: 'brand-profiles' },
    ],
    columns: ['title', 'sentiment_score', 'status'],
    hasAI: true,
    aiField: 'ai_analysis',
    scoreField: 'sentiment_score',
  },
  {
    key: 'multi-language',
    title: 'Multi-Language Voice',
    description: 'AI-powered brand voice adaptation and consistency across languages',
    icon: 'Globe',
    color: '#0ea5e9',
    gradient: 'linear-gradient(135deg, #0ea5e9, #38bdf8)',
    apiPath: '/api/multi-language',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'source_content', label: 'Source Content', type: 'textarea', required: true },
      { name: 'source_language', label: 'Source Language', type: 'select', options: ['English', 'Spanish', 'French', 'German', 'Japanese', 'Mandarin', 'Portuguese', 'Italian', 'Korean', 'Arabic', 'Hindi', 'Dutch', 'Swedish', 'Turkish', 'Russian', 'Polish'] },
      { name: 'target_language', label: 'Target Language', type: 'select', options: ['English', 'Spanish', 'French', 'German', 'Japanese', 'Mandarin', 'Portuguese', 'Italian', 'Korean', 'Arabic', 'Hindi', 'Dutch', 'Swedish', 'Turkish', 'Russian', 'Polish'] },
      { name: 'brand_profile_id', label: 'Brand Profile', type: 'select', optionsFrom: 'brand-profiles' },
    ],
    columns: ['title', 'source_language', 'target_language', 'quality_score', 'status'],
    hasAI: true,
    aiField: 'ai_analysis',
    scoreField: 'quality_score',
  },
];

// 8 new AI tools (advanced) — fired via POST /api/ai/<endpoint>
export const aiToolsConfig = [
  {
    key: 'voice-drift',
    title: 'Brand Voice Drift Detector',
    description: 'Detect drift between baseline and recent brand corpus',
    icon: 'Activity',
    color: '#ef4444',
    apiPath: '/api/ai/voice-drift',
    fields: [
      { name: 'brand_profile_id', label: 'Brand Profile', type: 'select', optionsFrom: 'brand-profiles' },
      { name: 'baseline_samples', label: 'Baseline Samples (one per line)', type: 'textarea', required: true, transform: 'lines' },
      { name: 'recent_samples', label: 'Recent Samples (one per line)', type: 'textarea', required: true, transform: 'lines' },
      { name: 'window_days', label: 'Window (days)', type: 'number', placeholder: '30' },
    ],
  },
  {
    key: 'audience-persona',
    title: 'Audience Persona Analyzer',
    description: 'Identify which persona resonates with content',
    icon: 'Users',
    color: '#6366f1',
    apiPath: '/api/ai/audience-persona',
    fields: [
      { name: 'content', label: 'Content', type: 'textarea', required: true },
      { name: 'channel', label: 'Channel', type: 'text' },
      { name: 'brand_profile_id', label: 'Brand Profile', type: 'select', optionsFrom: 'brand-profiles' },
    ],
  },
  {
    key: 'competitor-benchmark',
    title: 'Cross-Brand Competitive Benchmark',
    description: 'Benchmark our brand voice vs competitors',
    icon: 'BarChart3',
    color: '#f59e0b',
    apiPath: '/api/ai/competitor-benchmark',
    fields: [
      { name: 'our_brand_samples', label: 'Our Samples (one per line)', type: 'textarea', transform: 'lines' },
      { name: 'competitors', label: 'Competitors JSON [{"name":"X","samples":["..."]}]', type: 'textarea', required: true, transform: 'json' },
    ],
  },
  {
    key: 'variation-generator',
    title: 'Content Variation Generator',
    description: 'Generate 5 tone variations of the same content',
    icon: 'Shuffle',
    color: '#10b981',
    apiPath: '/api/ai/variation-generator',
    fields: [
      { name: 'content', label: 'Original Content', type: 'textarea', required: true },
      { name: 'tones', label: 'Tones (comma-separated)', type: 'text', placeholder: 'formal, playful, technical, conversational, urgent', transform: 'csv' },
    ],
  },
  {
    key: 'vocab-compliance',
    title: 'Vocabulary Compliance Checker',
    description: 'Flag banned/restricted terms; suggest approved alternatives',
    icon: 'CheckCircle',
    color: '#14b8a6',
    apiPath: '/api/ai/vocab-compliance',
    fields: [
      { name: 'content', label: 'Content', type: 'textarea', required: true },
      { name: 'brand_profile_id', label: 'Brand Profile', type: 'select', optionsFrom: 'brand-profiles' },
    ],
  },
  {
    key: 'channel-tone',
    title: 'Channel-Specific Tone Recommender',
    description: 'Optimal tone & rewrite per channel',
    icon: 'Radio',
    color: '#8b5cf6',
    apiPath: '/api/ai/channel-tone',
    fields: [
      { name: 'content', label: 'Original Content', type: 'textarea', required: true },
      { name: 'channels', label: 'Channels (comma-separated)', type: 'text', placeholder: 'linkedin, twitter, tiktok, instagram, email', transform: 'csv' },
    ],
  },
  {
    key: 'heritage-consistency',
    title: 'Brand Heritage Consistency Tracker',
    description: 'Compare current vs historical brand messaging',
    icon: 'Clock',
    color: '#a855f7',
    apiPath: '/api/ai/heritage-consistency',
    fields: [
      { name: 'historical_samples', label: 'Historical Samples (one per line)', type: 'textarea', required: true, transform: 'lines' },
      { name: 'current_samples', label: 'Current Samples (one per line)', type: 'textarea', required: true, transform: 'lines' },
      { name: 'brand_profile_id', label: 'Brand Profile', type: 'select', optionsFrom: 'brand-profiles' },
    ],
  },
  {
    key: 'approval-workflow',
    title: 'Multi-Team Approval Workflow',
    description: 'AI-driven approval routing with consistency score',
    icon: 'GitMerge',
    color: '#0ea5e9',
    apiPath: '/api/ai/approval-workflow',
    fields: [
      { name: 'content', label: 'Content', type: 'textarea', required: true },
      { name: 'brand_profile_id', label: 'Brand Profile', type: 'select', optionsFrom: 'brand-profiles' },
      { name: 'submitter_role', label: 'Submitter Role', type: 'text', placeholder: 'contributor, lead, exec' },
      { name: 'channel', label: 'Channel', type: 'text' },
    ],
  },
  {
    key: 'readability-score',
    title: 'Readability Score Analyzer',
    description: 'Analyze Flesch-Kincaid grade level, reading time, complexity and passive voice',
    icon: 'BarChart3',
    color: '#06b6d4',
    apiPath: '/api/ai/readability-score',
    fields: [
      { name: 'content', label: 'Content to Analyze', type: 'textarea', required: true },
      { name: 'brand_profile_id', label: 'Brand Profile', type: 'select', optionsFrom: 'brand-profiles' },
    ],
  },
  {
    key: 'tone-rewriter',
    title: 'One-Click Tone Rewriter',
    description: 'Instantly rewrite content to match a target tone while preserving meaning',
    icon: 'Shuffle',
    color: '#f43f5e',
    apiPath: '/api/ai/tone-rewriter',
    fields: [
      { name: 'content', label: 'Original Content', type: 'textarea', required: true },
      { name: 'desired_tone', label: 'Desired Tone', type: 'text', placeholder: 'formal, playful, urgent, empathetic...', required: true },
      { name: 'brand_profile_id', label: 'Brand Profile', type: 'select', optionsFrom: 'brand-profiles' },
    ],
  },
];
